/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reproductor;

import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javazoom.jlgui.basicplayer.BasicPlayer;
import javazoom.jlgui.basicplayer.BasicPlayerException;

/**
 *
 * @author emanuel
 */
public class Reproductor extends javax.swing.JFrame {
    
    /** Lista de canciones */
    public ArrayList<Cancion> canciones;
    
    /** Lista de PlayList*/
    public ArrayList<Playlist> playLists;
    
    /** Player auxiliar. */
    private final BasicPlayer player;
    
    private final Icon iconoPlay;
    
    private final Icon iconoPause;
    
    private boolean reproduciendo;

    /**
     * Creates new form Reproductor
     */
    public Reproductor() {
        initComponents();
        
        cancionActual.setForeground(java.awt.Color.cyan);
        
        //fondo
        ImageIcon fondo = new ImageIcon("src/Reproductor/Fondo.jpg");
        Icon iconoFondo = new ImageIcon(fondo.getImage().getScaledInstance(wallpaper.getWidth(), wallpaper.getHeight(), Image.SCALE_DEFAULT));
        wallpaper.setIcon(iconoFondo);
        
        //Boton Play
        ImageIcon botonPlay = new ImageIcon("src/Reproductor/PLAY.png");
        iconoPlay = new ImageIcon(botonPlay.getImage().getScaledInstance(playBoton.getWidth(), playBoton.getHeight(), Image.SCALE_DEFAULT));
        playBoton.setIcon(iconoPlay);
        
        ImageIcon botonPause = new ImageIcon("src/Reproductor/PAUSE.png");
        iconoPause = new ImageIcon(botonPause.getImage().getScaledInstance(playBoton.getWidth(), playBoton.getHeight(), Image.SCALE_DEFAULT));
        
        //Boton Derecho
        ImageIcon botonDer = new ImageIcon("src/Reproductor/DER.png");
        Icon iconoDer = new ImageIcon(botonDer.getImage().getScaledInstance(derBoton.getWidth(), derBoton.getHeight(), Image.SCALE_DEFAULT));
        derBoton.setIcon(iconoDer);
        
        //Boton Izquierdo
        ImageIcon botonIzq = new ImageIcon("src/Reproductor/IZQ.png");
        Icon iconoIzq = new ImageIcon(botonIzq.getImage().getScaledInstance(izqBoton.getWidth(), izqBoton.getHeight(), Image.SCALE_DEFAULT));
        izqBoton.setIcon(iconoIzq);

        //Boton repetir
        ImageIcon botonRepetir = new ImageIcon("src/Reproductor/REPETIR.png");
        Icon iconoRep = new ImageIcon(botonRepetir.getImage().getScaledInstance(repetir.getWidth(), repetir.getHeight(), Image.SCALE_DEFAULT));
        repetir.setIcon(iconoRep);
        
        //Boton aleatorio
        ImageIcon botonAleatorio = new ImageIcon("src/Reproductor/ALEATORIO.png");
        Icon iconoAle = new ImageIcon(botonAleatorio.getImage().getScaledInstance(aleatorio.getWidth(), aleatorio.getHeight(), Image.SCALE_DEFAULT));
        aleatorio.setIcon(iconoAle);
        
        player = new BasicPlayer();
        
        reproduciendo = false;
    }
    
    /**
     * Agrega una cancion al Reproductor.
     * @param cancion
     */
    public void agregaCancion(Cancion cancion){
        canciones.add(cancion);
    }
    
    /**
     * Elimina una cancion del Reproductor.
     * @param cancion
     */
    public void eliminar(Cancion cancion){
        canciones.remove(cancion);
    }
    
    /**
     * Crea una PlayList al Reproductor.
     * @param playlist
     */
    public void crearPlayList(Playlist playlist){
        playLists.add(playlist);
    }
    
    /**
     * Elimina una PlayList del Reproductor.
     * @param playlist
     */
    public void eliminarPlayList(Playlist playlist){
        playLists.remove(playlist);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        portada = new javax.swing.JLabel();
        cancionActual = new javax.swing.JLabel();
        playBoton = new javax.swing.JButton();
        derBoton = new javax.swing.JButton();
        izqBoton = new javax.swing.JButton();
        repetir = new javax.swing.JButton();
        aleatorio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        wallpaper = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(900, 460));
        getContentPane().setLayout(null);

        jButton2.setText("Canciones");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 30, 140, 37);

        jButton3.setText("Playlists");
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 80, 140, 37);

        jButton4.setText("Elimina Canción");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(10, 180, 140, 37);

        jButton5.setText("Agrega Canción");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(10, 130, 140, 37);

        jButton6.setText("Agrega Playlist");
        getContentPane().add(jButton6);
        jButton6.setBounds(10, 230, 140, 37);

        jButton7.setText("Busca Canción");
        getContentPane().add(jButton7);
        jButton7.setBounds(10, 280, 140, 37);
        getContentPane().add(portada);
        portada.setBounds(370, 30, 580, 280);

        cancionActual.setFont(new java.awt.Font("Baekmuk Headline", 2, 24)); // NOI18N
        cancionActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancionActual.setText("REPRODUCTOR EN PAUSA");
        getContentPane().add(cancionActual);
        cancionActual.setBounds(250, 310, 540, 30);

        playBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBotonActionPerformed(evt);
            }
        });
        getContentPane().add(playBoton);
        playBoton.setBounds(510, 357, 80, 70);
        getContentPane().add(derBoton);
        derBoton.setBounds(620, 357, 80, 70);

        izqBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izqBotonActionPerformed(evt);
            }
        });
        getContentPane().add(izqBoton);
        izqBoton.setBounds(400, 360, 80, 70);

        repetir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repetirActionPerformed(evt);
            }
        });
        getContentPane().add(repetir);
        repetir.setBounds(720, 370, 80, 50);
        getContentPane().add(aleatorio);
        aleatorio.setBounds(300, 370, 80, 50);

        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(170, 30, 170, 280);
        getContentPane().add(wallpaper);
        wallpaper.setBounds(0, 0, 900, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    // BOTÓN AGREGA CANCIÓN
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        JFileChooser jfc = new JFileChooser();  
        int returnValue = jfc.showOpenDialog(null);
        
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jfc.getSelectedFile();
            
            try {
                player.open(selectedFile);
            } catch (BasicPlayerException ex) {
                Logger.getLogger(Reproductor.class.getName()).log(Level.SEVERE, null, ex);
            }
        }     
    }//GEN-LAST:event_jButton5ActionPerformed

    private void izqBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izqBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_izqBotonActionPerformed

    private void repetirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repetirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_repetirActionPerformed

    private void playBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBotonActionPerformed
        
        if(reproduciendo){
            try {
                player.pause();
                playBoton.setIcon(iconoPlay);
            } catch (BasicPlayerException ex) {
                Logger.getLogger(Reproductor.class.getName()).log(Level.SEVERE, null, ex);
            }
            reproduciendo = false;
            return;
        }
            
            try {
                player.play();
            } catch (BasicPlayerException ex) {
                Logger.getLogger(Reproductor.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        playBoton.setIcon(iconoPause);
        reproduciendo = true;
    }//GEN-LAST:event_playBotonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Reproductor().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aleatorio;
    private javax.swing.JLabel cancionActual;
    private javax.swing.JButton derBoton;
    private javax.swing.JButton izqBoton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton playBoton;
    private javax.swing.JLabel portada;
    private javax.swing.JButton repetir;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
